RUN_STRINGS = (
    "Sekarang kamu melihatku, sekarang kamu tidak."  "ε=ε=ε=ε=┌(;￣▽￣)┘" ,
    "Kembali kesini!" ,
    "REEEEEEEEEEEEEEEEEE!!!!!!!!" ,
    "Awas tembok!" ,
    "Jangan tinggalkan aku sendiri dengan mereka!!" ,
    "Kamu punya teman!" ,
    "Chottomatte!" ,
    "Yare yare linglung" ,
    "*Naruto run diaktifkan*" ,
    "*Nezuko dijalankan diaktifkan*" ,
    "Hah? apa? mereka kabur?" ,
    "Kembali kesini!" ,
    "Awas tembok!" ,
    "Jangan tinggalkan aku sendiri dengan mereka!!" ,
    "Kamu punya teman!" ,
    "Chottomatte!" ,
    "Yare yare linglung" ,
    "Hei, bertanggung jawab atas apa yang baru saja kamu lakukan!" ,
    "Semoga peluang selalu menguntungkan Anda." ,
    "Lari semuanya, mereka baru saja menjatuhkan bom 💣💣" ,
    "Dan mereka menghilang selamanya, tidak pernah terlihat lagi." ,
    "Legenda mengatakannya, mereka masih berlari." ,
    "Hasta la vista, sayang." ,
    "Ah, sayang sekali. Aku suka yang itu." ,
    "Seperti kata Dokter... LARI!" ,
)

SLAP_GOJO_TEMPLATES = (
    "Tampar aku sekali lagi dan aku akan membungkammu." ,
    "Jangan berani menamparku lagi ||ASSH-0-LE||." ,
)

SLAP_TEMPLATES = (
    "{user2} dibunuh oleh sihir." ,
    "{user2} kelaparan tanpa tepukan." ,
    "{user2} dijatuhkan ke dalam kekosongan oleh {user1}." ,
    "{user2} pingsan." ,
    "{user2} kehabisan Pokemon yang bisa digunakan! {user2} mati total!." ,
    "{user2} kehabisan Pokemon yang bisa digunakan! {user2} pingsan!." ,
    "{user2} punya rekt." ,
    "Melon {pengguna2} dibelah oleh {pengguna1}." ,
    "{user2} diiris dan dipotong dadu oleh {user1}." ,
    "{user2} bermain hot-potato dengan granat." ,
    "{user2} ditusuk oleh {user1}." ,
    "{user2} makan granat." ,
    "{user2} untuk makan malam!" ,
    "{user2} dihentikan oleh {user1}." ,
    "{user1} mengirim spam ke email {user2}." ,
    "{user1} mengenkripsi RSA {user2} dan menghapus kunci pribadi." ,
    "{user1} tempatkan {user2} di zona pertemanan." ,
    "{user1} menampar {user2} dengan permintaan penghapusan DMCA!" ,
    "{user2} mendapat telepon rumah dari Dokter {user1}." ,
    "{user1} memenggal {user2}." ,
    "{user2} dilempari batu...oleh massa yang marah." ,
    "{user1} menggugat celana {user2}." ,
    "{user2} adalah KO satu pukulan oleh {user1}." ,
    "{user1} mengirim {user2} ke lubang memori." ,
    "{user2} adalah sebuah kesalahan. - '{user1}' " ,
    "{user2} dibuat mubazir." ,
    "{user1} {memukul} {user2} dengan kelelawar!." ,
    "{user1} {hits} {user2} dengan Jurus Taijutsu!." ,
    "{user1} {hits} {user2} dengan X-Gloves!." ,
    "{user1} {hits} {user2} dengan Jet Punch!." ,
    "{user1} {memukul} {user2} dengan Jet Pistol!." ,
    "{user1} {hits} {user2} dengan United States of Smash!." ,
    "{user1} {hits} {user2} dengan Detroit Smash!." ,
    "{user1} {hits} {user2} dengan Texas Smash!." ,
    "{user1} {hits} {user2} dengan California Smash!." ,
    "{user1} {hits} {user2} dengan New Hampshire Smash!." ,
    "{user1} {hits} {user2} dengan Missouri Smash!." ,
    "{user1} {hits} {user2} dengan Carolina Smash!." ,
    "{user1} {memukul} {user2} dengan King Kong Gun!." ,
    "{user1} {memukul} {user2} dengan tongkat bisbol - logam.!." ,
    "* Pukulan serius {user2}*." ,
    "* Pukulan biasa {user2}*." ,
    "* Pukulan normal berturut-turut {user2}*." ,
    "* Pukulan Normal Dua Tangan Berturut-turut {user2}*." ,
    "*Abaikan {user2} untuk membiarkan mereka mati karena malu*." ,
    "* menunjuk ke {user2}* Ada apa dengan lancang... anak hilang ini?." ,
    "*Pukul {user2} dengan Fire Tornado*." ,
    "{user1} menusuk mata {user2}!" ,
    "{user1} menyodok {user2} di samping!" ,
    "{user1} colek {user2}!" ,
    "{user1} menusuk {user2} dengan jarum!" ,
    "{user1} menusuk {user2} dengan pena!" ,
    "{user1} menusuk {user2} dengan senjata bius!" ,
    "{user2} diam-diam adalah Furry!" ,
    "Hai Semuanya! {user1} meminta saya untuk menjadi jahat!" ,
    "( ･_･)ﾉ⌒●~* (･.･;) <-{pengguna2}" ,
    "Ambil ini {user2} \n (ﾉﾟДﾟ)ﾉ ))))●~* " ,
    "Sini {user2} pegang ini \n (｀・ω・)つ ●~＊" ,
    "( ・_・)ノΞ●~* {pengguna2} \n Dieeeeee!!." ,
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n *Bug menyemprot {user2}*." ,
    "( ﾟДﾟ)ﾉ占~<巛巛巛. \n -{pengguna2} Kamu menyebalkan!" ,
    "( う-´)づ︻╦̵̵̿╤── \\(˚☐˚”)/ {user2}.",
    "{user1} {memukul} {user2} dengan {item}." ,
    "{user1} {hits} {user2} di muka dengan {item}." ,
    "{user1} {hits} {user2} sedikit dengan {item}." ,
    "{user1} {melempar} {item} ke {user2}." ,
    "{user1} mengambil {item} dan {melemparnya} ke wajah {user2}." ,
    "{user1} meluncurkan {item} ke arah umum {user2}." ,
    "{user1} mulai menampar {user2} konyol dengan {item}." ,
    "{user1} menyematkan {user2} ke bawah dan berulang kali {memukul} mereka dengan {item}." ,
    "{user1} mengambil {item} dan {hits} {user2} dengan itu." ,
    "{user1} mengikat {user2} ke kursi dan {melempar} {item} ke arah mereka." ,
    "{user1} memberikan dorongan ramah untuk membantu {user2} belajar berenang di lahar." ,
    "{user1} menindas {user2}." ,
    "Nyaan memakan kaki {user2}. *nomnomnom*" ,
    "{user1} {melempar} bola master ke {user2}, perlawanan sia-sia." ,
    "{user1} mengenai {user2} dengan action beam...bbbbbb (ง・ω・)ง ====*" ,
    "{user1} ara ara {user2}." ,
    "{user1} ora ora {user2}." ,
    "{user1} muda muda {user2}." ,
    "{user2} diubah menjadi referensi Jojo!" ,
    "{user1} memukul {user2} dengan {item}." ,
    "Ronde 2!..Siap?.. FIGHT!!" ,
    "WhoPixel akan menghasilkan {user2} hingga tak terbatas dan seterusnya." ,
    "{user2} makan kelelawar dan menemukan penyakit baru." ,
    "{user1} melipat {user2} menjadi bidang kertas" ,
    "{user1} menghidangkan {user2} sup kelelawar." ,
    "{user2} dikirim ke rumahnya, planet kera." ,
    "{user1} menendang {user2} dari kereta yang bergerak." ,
    "{user2} baru saja membunuh anjing John Wick." ,
    "{user1} melakukan mantra Avada Kedavra pada {user2}." ,
    "{user1} membuat {user2} menjadi tungku api." ,
    "Sakura Haruno menjadi lebih berguna daripada {user2}" ,
    "{user1} mencabut dukungan hidup {user2}." ,
    "{user1} berlangganan {user2}' ke internet buruk selama 5 tahun." ,
    "Kamu tahu apa yang lebih buruk dari lelucon Ayah? {user2}!" ,
    "{user1} mengambil semua cookie {user2}." ,
    "{user2} wa mou.......Shindeiru! - {user1}." ,
    "{user2} kehilangan bidak rasnya!" ,   # Tidak ada permainan tidak ada referensi kehidupan
    "Diam {user2}, kamu hanya {user2}." ,   # Tidak ada permainan tidak ada referensi kehidupan
    "{user1} memukul {user2} dengan Aka si anse!" ,   # Tidak ada permainan tidak ada referensi kehidupan
    "@NeoTheKitty mencakar {user2}" ,   kucing peliharaan # Piksel - @NeoTheKitty
    "Majin buu makan {user2}" ,   # Dbz
    "Pembunuh Goblin membunuh {user2}" ,   # Pembunuh Goblin
    "{user2} ditembak oleh {user1}." ,
    "{user2} masuk ke kaktus sambil mencoba melarikan diri {user1}." ,
    "{user2} tenggelam saat mencoba melarikan diri {user1}." ,
    "{user2} jatuh ke sepetak kaktus." ,
    "{user2} terbakar." ,
    "{user2} terbakar sampai mati." ,
    "{user2} dibakar habis saat melawan {user1}." ,
    "{user2} tersambar petir." ,
    "{user2} dibunuh oleh {user1}." ,
    "{user2} dibunuh oleh sihir." ,
    "{user2} mati kelaparan." ,
    "{user2} jatuh dari dunia." ,
    "{user2} dijatuhkan ke dalam kekosongan oleh {user1}." ,
    "Tulang {pengguna2} tergores bersih oleh angin sunyi." ,
    "{user2} pingsan." ,
    "{user2} kehabisan Pokemon yang bisa digunakan! {user2} mati total!." ,
    "{user2} kehabisan Pokemon yang bisa digunakan! {user2} pingsan!." ,
    "{user2} mengucapkan selamat tinggal pada dunia yang kejam ini." ,
    "{user2} punya rekt." ,
    "{user2} digergaji menjadi dua oleh {user1}." ,
    "Melon {pengguna2} dibelah oleh {pengguna1}." ,
    "{user2} diiris dan dipotong dadu oleh {user1}." ,
    "Kematian {user2} membuat kedudukan lain di kapak {user1}." ,
    "{user2} meninggal karena penyakit tropis misterius {user1}." ,
    "{user2} bermain hot-potato dengan granat." ,
    "{user2} ditusuk oleh {user1}." ,
    "{user2} makan granat." ,
    "{user2} untuk makan malam!" ,
    "{user2} dihentikan oleh {user1}." ,
    "{user2} ditembak sebelum dilempar keluar dari pesawat." ,
    "{user2} mengalami kesalahan." ,
    "{user2} mati dan bereinkarnasi sebagai kambing." ,
    "{user1} melempar {user2} dari gedung." ,
    "{user2} mendapat penguburan prematur." ,
    "{user1} mengirim spam ke email {user2}." ,
    "{user1} menabrak {user2} dengan pesawat luar angkasa kecil antarbintang." ,
    "{user1} tempatkan {user2} di skakmat." ,
    "{user1} mengenkripsi RSA {user2} dan menghapus kunci pribadi." ,
    "{user1} tempatkan {user2} di zona pertemanan." ,
    "{user1} menampar {user2} dengan permintaan penghapusan DMCA!" ,
    "{user2} meninggal karena gangren rumah sakit." ,
    "{user2} mendapat telepon rumah dari Dokter {user1}." ,
    "{user1} memenggal {user2}." ,
    "{user2} dilempari batu...oleh massa yang marah." ,
    "{user1} menggugat celana {user2}." ,
    "{user2} adalah KO satu pukulan oleh {user1}." ,
    "{user1} mengirim {user2} ke lubang memori." ,
    "{user2} adalah sebuah kesalahan. - '{user1}' " ,
    "{user1} melakukan skakmat {user2} dalam dua gerakan." ,
    "{user2} dibuat mubazir." ,
    "{user1} {memukul} {user2} dengan kelelawar!." ,
    "{user1} {hits} {user2} dengan Jurus Taijutsu!." ,
    "{user1} {hits} {user2} dengan X-Gloves!." ,
    "{user1} {hits} {user2} dengan Jet Punch!." ,
    "{user1} {memukul} {user2} dengan Jet Pistol!." ,
    "{user1} {hits} {user2} dengan United States of Smash!." ,
    "{user1} {hits} {user2} dengan Detroit Smash!." ,
    "{user1} {hits} {user2} dengan Texas Smash!." ,
    "{user1} {hits} {user2} dengan California Smash!." ,
    "{user1} {hits} {user2} dengan New Hampshire Smash!." ,
    "{user1} {hits} {user2} dengan Missouri Smash!." ,
    "{user1} {hits} {user2} dengan Carolina Smash!." ,
    "{user1} {memukul} {user2} dengan King Kong Gun!." ,
    "{user1} {memukul} {user2} dengan tongkat bisbol - logam.!." ,
    "* Pukulan serius {user2}*." ,
    "* Pukulan biasa {user2}*." ,
    "* Pukulan normal berturut-turut {user2}*." ,
    "* Pukulan Normal Dua Tangan Berturut-turut {user2}*." ,
    "*Abaikan {user2} untuk membiarkan mereka mati karena malu*." ,
    "* menunjuk ke {user2}* Ada apa dengan lancang... anak hilang ini?." ,
    "*Pukul {user2} dengan Fire Tornado*." ,
    "{user1} menusuk mata {user2}!" ,
    "{user1} menyodok {user2} di samping!" ,
    "{user1} colek {user2}!" ,
    "{user1} menusuk {user2} dengan jarum!" ,
    "{user1} menusuk {user2} dengan pena!" ,
    "{user1} menusuk {user2} dengan senjata bius!" ,
    "{user2} diam-diam adalah Furry!." ,
    "Hai Semuanya! {user1} meminta saya untuk menjadi jahat!" ,
    "( ･_･)ﾉ⌒●~* (･.･;) <-{pengguna2}" ,
    "Ambil ini {user2} \n (ﾉﾟДﾟ)ﾉ ))))●~* " ,
    "Sini {user2} pegang ini \n (｀・ω・)つ ●~＊" ,
    "( ・_・)ノΞ●~* {pengguna2} \n Dieeeeee!!." ,
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n *Bug menyemprot {user2}*." ,
    "( ﾟДﾟ)ﾉ占~<巛巛巛. \n -{pengguna2} Kamu menyebalkan!" ,
    r"( う-´)づ︻╦̵̵̿╤── \(˚☐˚")/ {pengguna2}." ,
    "{user1} {memukul} {user2} dengan {item}." ,
    "{user1} {hits} {user2} di muka dengan {item}." ,
    "{user1} {hits} {user2} sedikit dengan {item}." ,
    "{user1} {melempar} {item} ke {user2}." ,
    "{user1} mengambil {item} dan {melemparnya} ke wajah {user2}." ,
    "{user1} meluncurkan {item} ke arah umum {user2}." ,
    "{user1} mulai menampar {user2} konyol dengan {item}." ,
    "{user1} menyematkan {user2} ke bawah dan berulang kali {memukul} mereka dengan {item}." ,
    "{user1} mengambil {item} dan {hits} {user2} dengan itu." ,
    "{user1} mengikat {user2} ke kursi dan {melempar} {item} ke arah mereka." ,
    "{user1} memberikan dorongan ramah untuk membantu {user2} belajar berenang di lahar." ,
    "{user1} menindas {user2}." ,
    "Nyaan memakan kaki {user2}. *nomnomnom*" ,
    "{user1} {melempar} bola master ke {user2}, perlawanan sia-sia." ,
    "{user1} mengenai {user2} dengan action beam...bbbbbb (ง・ω・)ง ====*" ,
    "{user1} ara ara {user2}." ,
    "{user1} ora ora {user2}." ,
    "{user1} muda muda {user2}." ,
    "{user2} diubah menjadi referensi Jojo!" ,
    "{user1} memukul {user2} dengan {item}." ,
    "Ronde 2!..Siap?.. FIGHT!!" ,
    "WhoPixel akan menghasilkan {user2}, hingga tak terbatas dan seterusnya."
    "{user2} makan kelelawar dan menemukan penyakit baru." ,
    "{user1} melipat {user2} menjadi bidang kertas" ,
    "{user1} menukar daya hidup {user2} dengan secangkir cokelat." ,
    "{user2} melakukan 69 dengan kaktus." ,
    "{user1} menghidangkan {user2} sup kelelawar." ,
    "{user2} dikirim ke rumahnya, planet kera." ,
    "{user1} menendang {user2} dari kereta yang bergerak." ,
    "{user1} melakukan perjalanan ke masa depan dan meludahi makam {user2}." ,
    "{user2} meninggal karena bicara-tanpa-jutsu." ,
    "{user2} ditempatkan sebagai karpet untuk kompetisi stomp dance." ,
    "{user2} baru saja membunuh anjing John Wick." ,
    "{user1} melakukan mantra Avada Kedavra pada {user2}." ,
    "{user1} membuat {user2} menjadi tungku api." ,
    "Sakura Haruno menjadi lebih berguna daripada {user2}" ,
    "{user1} mencabut dukungan hidup {user2}." ,
    "{user1} berlangganan {user2}' ke internet buruk selama 5 tahun." ,
    "{user1} belajar mengapa menjadi dokter gigi buaya adalah ide yang buruk." ,
    "Kamu tahu apa yang lebih buruk dari lelucon Ayah? {user2}!" ,
    "{user1} mengambil semua cookie {user2}." ,
)

ITEMS = (
    "wajan besi" ,
    "meong marah" ,
    "pemukul kriket" ,
    "tongkat kayu" ,
    "sekop" ,
    "pemanggang" ,
    "buku" ,
    "laptop" ,
    "ayam karet" ,
    "kelelawar berduri" ,
    "batu berat" ,
    "kotoran" ,
    "ton batu bata" ,
    "rasengan" ,
    "bom roh" ,
    "Bodhisattva Guanyin Tipe 100" ,
    "rasenshuriken" ,
    "Murasame" ,
    "larangan" ,
    "chunchunmaru" ,
    "Kubikiribōchō" ,
    "rasengan" ,
    "kat terbang bulat" ,
    "burung pemarah" ,
    "egomu" ,
)

THROW = (
    "melempar" ,
    "teman kencan" ,
    "membuang" ,
    "melemparkan" ,
)

HIT = ("hit", "mengalahkan", "menampar", "memukul", "tamparan", "Tepukan")

REACTIONS = (
    "( ͡° ͜ʖ ͡°)",
    "( . •́ _ʖ •̀ .)",
    "( ಠ ͜ʖ ಠ)",
    "( ͡ ͜ʖ ͡ )",
    "(ʘ ͜ʖ ʘ)",
    "ヾ(´〇`)ﾉ♪♪♪",
    "ヽ(o´∀`)ﾉ♪♬",
    "♪♬((d⌒ω⌒b))♬♪",
    "└(＾＾)┐",
    "(￣▽￣)/♫•*¨*•.¸¸♪",
    "ヾ(⌐■_■)ノ♪",
    "乁( • ω •乁)",
    "♬♫♪◖(● o ●)◗♪♫♬",
    "(っ˘ڡ˘ς)",
    "( ˘▽˘)っ♨",
    "(　・ω・)⊃-[二二]",
    "(*´ー`)旦 旦(￣ω￣*)",
    "( ￣▽￣)[] [](≧▽≦ )",
    "(*￣▽￣)旦 且(´∀`*)",
    "(ノ ˘_˘)ノ　ζ|||ζ　ζ|||ζ　ζ|||ζ",
    "(ノ°∀°)ノ⌒･*:.｡. .｡.:*･゜ﾟ･*☆",
    "(⊃｡•́‿•̀｡)⊃━✿✿✿✿✿✿",
    "(∩` ﾛ ´)⊃━炎炎炎炎炎",
    "( ・∀・)・・・--------☆",
    "( -ω-)／占~~~~~",
    "○∞∞∞∞ヽ(^ー^ )",
    "(*＾＾)/~~~~~~~~~~◎",
    "((( ￣□)_／",
    "(ﾒ￣▽￣)︻┳═一",
    "ヽ( ･∀･)ﾉ_θ彡☆Σ(ノ `Д´)ノ",
    "(*`0´)θ☆(メ°皿°)ﾉ",
    "(; -_-)――――――C<―_-)",
    "ヽ(>_<ヽ) ―⊂|=0ヘ(^‿^ )",
    "(҂` ﾛ ´)︻デ═一 ＼(º □ º l|l)/",
    "/( .□.)＼ ︵╰(°益°)╯︵ /(.□. /)",
    "(`⌒*)O-(`⌒´Q)",
    "(っ•﹏•)っ ✴==≡눈٩(`皿´҂)ง",
    "ヾ(・ω・)メ(・ω・)ノ",
    "(*^ω^)八(⌒▽⌒)八(-‿‿- )ヽ",
    "ヽ( ⌒ω⌒)人(=^‥^= )ﾉ",
    "｡*:☆(・ω・人・ω・)｡:゜☆｡",
    "(°(°ω(°ω°(☆ω☆)°ω°)ω°)°)",
    "(っ˘▽˘)(˘▽˘)˘▽˘ς)",
    "(*＾ω＾)人(＾ω＾*)",
    r"＼(▽￣ \ (￣▽￣) / ￣▽)／",
    "(￣Θ￣)",
    "＼( ˋ Θ ´ )／",
    "( ´(00)ˋ )",
    "＼(￣(oo)￣)／",
    "／(≧ x ≦)＼",
    "／(=･ x ･=)＼",
    "(=^･ω･^=)",
    "(= ; ｪ ; =)",
    "(=⌒‿‿⌒=)",
    "(＾• ω •＾)",
    "ଲ(ⓛ ω ⓛ)ଲ",
    "ଲ(ⓛ ω ⓛ)ଲ",
    "(^◔ᴥ◔^)",
    "[(－－)]..zzZ",
    "(￣o￣) zzZZzzZZ",
    "(＿ ＿*) Z z z",
    "☆ﾐ(o*･ω･)ﾉ",
    "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "ε===(っ≧ω≦)っ",
    "__φ(．．)",
    "ヾ( `ー´)シφ__",
    "( ^▽^)ψ__",
    "|･ω･)",
    "|д･)",
    "┬┴┬┴┤･ω･)ﾉ",
    "|･д･)ﾉ",
    "(*￣ii￣)",
    "(＾〃＾)",
    "m(_ _)m",
    "人(_ _*)",
    "(シ. .)シ",
    "(^_~)",
    "(>ω^)",
    "(^_<)〜☆",
    "(^_<)",
    "(づ￣ ³￣)づ",
    "(⊃｡•́‿•̀｡)⊃",
    "⊂(´• ω •`⊂)",
    "(*・ω・)ﾉ",
    "(^-^*)/",
    "ヾ(*'▽'*)",
    "(^０^)ノ",
    "(*°ｰ°)ﾉ",
    "(￣ω￣)/",
    "(≧▽≦)/",
    "w(°ｏ°)w",
    "(⊙_⊙)",
    "(°ロ°) !",
    "∑(O_O;)",
    "(￢_￢)",
    "(¬_¬ )",
    "(↼_↼)",
    "(￣ω￣;)",
    "┐('～`;)┌",
    "(・_・;)",
    "(＠_＠)",
    "(•ิ_•ิ)?",
    "ヽ(ー_ー )ノ",
    "┐(￣ヘ￣)┌",
    "┐(￣～￣)┌",
    "┐( ´ д ` )┌",
    "╮(︶▽︶)╭",
    "ᕕ( ᐛ )ᕗ",
    "(ノωヽ)",
    "(″ロ゛)",
    "(/ω＼)",
    "(((＞＜)))",
    "~(>_<~)",
    "(×_×)",
    "(×﹏×)",
    "(ノ_<。)",
    "(μ_μ)",
    "o(TヘTo)",
    "( ﾟ，_ゝ｀)",
    "( ╥ω╥ )",
    "(／ˍ・、)",
    "(つω`｡)",
    "(T_T)",
    "o(〒﹏〒)o",
    "(＃`Д´)",
    "(・`ω´・)",
    "( `ε´ )",
    "(ﾒ` ﾛ ´)",
    "Σ(▼□▼メ)",
    "(҂ `з´ )",
    "٩(╬ʘ益ʘ╬)۶",
    "↑_(ΦwΦ)Ψ",
    "(ﾉಥ益ಥ)ﾉ",
    "(＃＞＜)",
    "(；￣Д￣)",
    "(￢_￢;)",
    "(＾＾＃)",
    "(￣︿￣)",
    "ヾ( ￣O￣)ツ",
    "(ᗒᗣᗕ)՞",
    "(ノ_<。)ヾ(´ ▽ ` )",
    "ヽ(￣ω￣(。。 )ゝ",
    "(ﾉ_；)ヾ(´ ∀ ` )",
    "(´-ω-`( _ _ )",
    "(⌒_⌒;)",
    "(*/_＼)",
    "( ◡‿◡ *)",
    "(//ω//)",
    "(￣▽￣*)ゞ",
    "(„ಡωಡ„)",
    "(ﾉ´ з `)ノ",
    "(♡-_-♡)",
    "(─‿‿─)♡",
    "(´ ω `♡)",
    "(ღ˘⌣˘ღ)",
    "(´• ω •`) ♡",
    "╰(*´︶`*)╯♡",
    "(≧◡≦) ♡",
    "♡ (˘▽˘>ԅ( ˘⌣˘)",
    "σ(≧ε≦σ) ♡",
    "(˘∀˘)/(μ‿μ) ❤",
    "Σ>―(〃°ω°〃)♡→",
    "(* ^ ω ^)",
    "(o^▽^o)",
    "ヽ(・∀・)ﾉ",
    "(o･ω･o)",
    "(^人^)",
    "( ´ ω ` )",
    "(´• ω •`)",
    "╰(▔∀▔)╯",
    "(✯◡✯)",
    "(⌒‿⌒)",
    "(*°▽°*)",
    "(´｡• ᵕ •｡`)",
    "ヽ(>∀<☆)ノ",
    "＼(￣▽￣)／",
    "(o˘◡˘o)",
    "(╯✧▽✧)╯",
    "( ‾́ ◡ ‾́ )",
    "(๑˘︶˘๑)",
    "(´･ᴗ･ ` )",
    "( ͡° ʖ̯ ͡°)",
    "( ఠ ͟ʖ ఠ)",
    "( ಥ ʖ̯ ಥ)",
    "(≖ ͜ʖ≖)",
    "ヘ(￣ω￣ヘ)",
    "(ﾉ≧∀≦)ﾉ",
    "└(￣-￣└))",
    "┌(＾＾)┘",
    "(^_^♪)",
    "(〜￣△￣)〜",
    "(｢• ω •)｢",
    "( ˘ ɜ˘) ♬♪♫",
    "( o˘◡˘o) ┌iii┐",
    "♨o(>_<)o♨",
    "( ・・)つ―{}@{}@{}-",
    "(*´з`)口ﾟ｡ﾟ口(・∀・ )",
    "( *^^)o∀*∀o(^^* )",
    "-●●●-ｃ(・・ )",
    "(ﾉ≧∀≦)ﾉ ‥…━━━★",
    "╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ",
    "(∩ᄑ_ᄑ)⊃━☆ﾟ*･｡*･:≡( ε:)",
    "OwO",
)

TOSS = (
    "Heads",
    "Tails",
)


DECIDE = (""Ya." , "Tidak." , "Mungkin." , "Siapa yang peduli?" , "Tidak ada yang peduli tentang itu")

INSULT_STRINGS = [
    "`Owww ... Dasar idiot bodoh.`" ,
    "`Jangan minum dan mengetik.`" ,
    "`Perintah tidak ditemukan. Sama seperti otak Anda.`" ,
    "`Aturan bot 544 bagian 9 mencegah saya membalas manusia bodoh seperti Anda.`" ,
    "`Maaf, kami tidak menjual otak.`" ,
    "`Percayalah, kamu tidak normal.`" ,
    "`Saya yakin otak Anda terasa seperti baru, karena Anda tidak pernah menggunakannya.`" ,
    "`Jika saya ingin bunuh diri, saya akan memanjat ego Anda dan melompat ke IQ Anda.`" ,
    "`Kamu tidak berevolusi dari kera, mereka berevolusi dari kamu.`" ,
    "`Bahasa apa yang kamu gunakan? Karena kedengarannya seperti omong kosong.`" ,
    "`Kamu adalah bukti bahwa evolusi BISA terbalik.`" ,
    "`Saya ingin menanyakan berapa umur Anda, tetapi saya tahu Anda tidak dapat menghitung setinggi itu.`" ,
    "`Sebagai orang luar, apa pendapat Anda tentang umat manusia?`" ,
    "`Biasanya orang hidup dan belajar. Anda hanya hidup.`" ,
    "`Teruslah bicara, suatu hari nanti kamu akan mengatakan sesuatu yang cerdas!`.......||Tapi aku meragukannya||" ,
    "`Setiap orang memiliki hak untuk menjadi bodoh tetapi Anda menyalahgunakan hak istimewa.`" ,
    "`Maafkan aku telah menyakiti perasaanmu ketika aku menyebutmu bodoh. Kupikir kamu sudah tahu itu.`" ,
    "`Anda harus mencoba mencicipi sianida.`" ,
    "`Kamu harus mencoba tidur selamanya.`" ,
    "`Ambil pistol dan tembak dirimu sendiri.`" ,
    "`Cobalah mandi dengan Asam Klorida, bukan air.`" ,
    "`Go Green! Berhenti menghirup Oksigen.`" ,
    "`Tuhan sedang mencarimu. Kamu harus pergi untuk menemuinya.`" ,
    "`Anda harus Relawan untuk target dalam jarak tembak.`" ,
    "`Mencoba main tangkap dan lempar dengan RDX asyik.`" ,
    "`Orang-orang seperti Anda adalah alasan kami memiliki jari tengah.`" ,
    "`Ketika ibumu mengantarmu ke sekolah, dia mendapat tiket karena membuang sampah sembarangan.`" ,
    "`Kamu sangat jelek sehingga ketika kamu menangis, air mata mengalir di belakang kepalamu… hanya untuk menghindari wajahmu.`" ,
    "`Jika Anda berbicara di belakang saya maka Anda berada dalam posisi yang sempurna untuk mencium ||ASS||!.`" ,
    "`Awww! betapa imutnya.....aku bukan kamu`" ,
    "`Kamu sangat jelek sehingga jika satu arah melihatmu, mereka akan mengubah arah mereka ke yang lain ...`" ,
    "`Kamu menyerahkan otakmu kepada Tuhan, pergi dan ambillah...`" ,
    "`Jika Anda pikir Anda idiot...............maka Anda benar sekali...`" ,
]


BAN_GIFS = [
    "https://tenor.com/bMiwt.gif",
    "https://tenor.com/bqhVe.gif",
    "https://tenor.com/bsHe5.gif",
    "https://j.gifs.com/y5Pr8z.gif",
    "https://tenor.com/bfvQv.gif",
    "https://j.gifs.com/lO0lv6.gif",
    "https://tenor.com/bGMhb.gif",
    "https://tenor.com/bjZai.gif",
    "https://media.giphy.com/media/fe4dDMD2cAU5RfEaCU/giphy.gif",
    "https://tenor.com/bndta.gif",
    "https://tenor.com/bkyIr.gif",
    "https://media.giphy.com/media/UBqgQxKnUJqb8oZ2zc/giphy.gif",
    "https://media.giphy.com/media/tanIENriCOil3ndF3V/giphy.gif",
    "https://media.giphy.com/media/fwX4RUzdkdx9XUGow4/giphy.gif",
    "https://media.giphy.com/media/XVLfZCU6jDvMYqF1xS/giphy.gif",
    "https://media.giphy.com/media/BSAZJvFOOR0VqREKMg/giphy.gif",
    "https://media.giphy.com/media/CI4aCJUjJDJEj3Jgo4/giphy-downsized-large.gif",
    "https://media.giphy.com/media/0jcrQmPmyI5U532qL2/giphy.gif",
]

KICK_GIFS = [
    "https://tenor.com/bizBJ.gif",
    "https://tenor.com/bjPvj.gif",
    "https://tenor.com/bJMx3.gif",
    "https://tenor.com/bJCGL.gif",
    "https://tenor.com/bsIMJ.gif",
    "https://tenor.com/buURG.gif",
    "https://tenor.com/bNOj9.gif",
    "https://tenor.com/NfK8.gif",
    "https://tenor.com/ymZn.gif",
    "https://tenor.com/77Lu.gif",
    "https://tenor.com/bPD4I.gif",
    "https://tenor.com/bOGXo.gif",
    "https://tenor.com/bDLqs.gif",
    "https://media.giphy.com/media/u2LJ0n4lx6jF6/giphy.gif",
    "https://media.giphy.com/media/BSAZJvFOOR0VqREKMg/giphy.gif",
    "https://media.giphy.com/media/eDR7j2vjCFOUMJ9rT2/giphy.gif",
    "https://media.giphy.com/media/ERNKP5G7ihZNW6VW4Q/giphy.gif",
    "https://media.giphy.com/media/1r6xks2F0iHfbNvt4p/giphy.gif",
    "https://media.giphy.com/media/M7j1rkxm0X5z30Hyrs/giphy.gif",
    "https://media.giphy.com/media/rad9oJzU4hVafD8ZnT/giphy.gif",
    "https://media.giphy.com/media/TcliN5WDKBbnUQ15H3/giphy.gif",
    "https://media.giphy.com/media/y9pfUqY3uaT1MPXxYM/giphy.gif",
]


MUTE_GIFS = [
    "https://media.giphy.com/media/MpCxz9VLh6t8ceRb0r/giphy.gif",
    "https://media.giphy.com/media/HWl1atKEPAWcw/giphy.gif",
    "https://media.giphy.com/media/1xkynOSsb8eFpbEood/giphy.gif",
    "https://media.giphy.com/media/LmUAM5ImMNZd0nnkvn/giphy.gif",
    "https://media.giphy.com/media/JNlXHSSioDe7YGTC7D/giphy.gif",
    "https://media.giphy.com/media/t0iSe43jX8JH0Hb95a/giphy.gif",
    "https://media.giphy.com/media/P4CXV70NTC0umRI61S/giphy.gif",
    "https://media.giphy.com/media/Z0WPxDF7zpIHVPrYUN/giphy.gif",
    "https://media.giphy.com/media/gJS1pGTbXlSCWUe2pg/giphy.gif",
    "https://media.giphy.com/media/SIoetMN7j96O5perEV/giphy.gif",
    "https://media.giphy.com/media/PBZrH2uy9E5rPruuCX/giphy.gif",
    "https://media.giphy.com/media/Cew2qzlug9t3ACYrD5/giphy.gif",
    "https://media.giphy.com/media/PtIm7eUGKYIZbknqsO/giphy.gif",
    "https://media.giphy.com/media/EKbCY8OgdATSGBekxM/giphy.gif",
]

NOWYES = [
    """
YES          YES              YESYES
YESYES   YES         YES          YES
YES  YES YES       YES               YES
YES    YESYES     YES                YES
YES      YESYE         YES         YES
YES          YES               YESYES
          """
]

YESWNO = [
    """
NO       NO   NONONO            NONO
 NO     NO    NO                      NO         NO
   NONO       NO                       NO
      NO           NONO                      NO
      NO           NO                 NO          NO
      NO           NO                    NO        NO
      NO           NONONO           NONO
"""
]

StartPic = [
    "https://telegra.ph/file/0fa644d367faa2f885b86.jpg",
]
